services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: oclm
    volumes:
      - "./data:/docker-entrypoint-initdb.d"
    ports:
      - "5432:5432"

volumes:
  pgdata: